"""add hold_color to posts

Revision ID: 00633cd5d0e8
Revises: f3a2b1c0d9e8
Create Date: 2026-06-22 23:08:39.856460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00633cd5d0e8'
down_revision = 'f3a2b1c0d9e8'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: originally auto-generated as alter_column (TEXT -> String(120)) by
    # diffing models.py against a production db that already had these two
    # columns from an out-of-band change. That left no migration that actually
    # creates them, so building the schema from scratch (fresh db) failed with
    # "KeyError: 'city'". Changed to add_column so a from-scratch `flask db
    # upgrade` works; harmless for existing dbs since column presence is only
    # ever driven by this migration having run, and it already has everywhere
    # that matters.
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_color', sa.String(length=7), nullable=True))
        # Same gap as gyms.city/country above, but silent: posts.gym_id was
        # added out-of-band to production and models.py was updated at the
        # same time, so autogenerate never saw a diff to capture as a
        # migration. Discovered when a from-scratch dev db failed with
        # "OperationalError: table posts has no column named gym_id" on
        # first post creation.
        batch_op.add_column(sa.Column('gym_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posts_gym_id_gyms', 'gyms', ['gym_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_gym_id_gyms', type_='foreignkey')
        batch_op.drop_column('gym_id')
        batch_op.drop_column('hold_color')

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
