"""add hold_color to posts

Revision ID: 00633cd5d0e8
Revises: f3a2b1c0d9e8
Create Date: 2026-06-22 23:08:39.856460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00633cd5d0e8'
down_revision = 'f3a2b1c0d9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('hold_color')

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
