"""auto-generate username, add is_onboarded, drop reaction_palette

Revision ID: e3bc57fe7fec
Revises: 6e76f0f8540f
Create Date: 2026-05-14 15:03:36.622922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e3bc57fe7fec'
down_revision = '6e76f0f8540f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_onboarded', sa.Boolean(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('reaction_palette')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reaction_palette', sqlite.JSON(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('is_onboarded')

    # ### end Alembic commands ###
